image:
  repository: k8s.gcr.io/echoserver
  tag: 1.10
  port: 8080

env:
  MY_CONFIG: myconfig

autoscaling:
  enable: true
  maxReplica: 2
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
