apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: ${namespace}
  labels:
    app: aws-adot
    component: adot-collector-sa
  annotations:
    eks.amazonaws.com/role-arn: ${aws_role_arn}
